services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    container_name: platformflower-sqlserver
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - platformflower-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    # healthcheck:
      # test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P PlatformFlower123! -Q 'SELECT 1' || exit 1"]
      # interval: 30s
      # timeout: 10s
      # retries: 10
      # start_period: 60s

# Database Initialization
  db-init:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    container_name: platformflower-db-init
    depends_on:
      - sqlserver  # Removed condition: service_healthy
    volumes:
      - ./PlatformFlower/Scripts:/scripts
    networks:
      - platformflower-network
    environment:
      - ACCEPT_EULA=Y
    command: >
      bash -c "
        echo 'Waiting for SQL Server to be ready...'
        sleep 30
        echo 'Running database initialization script...'
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P PlatformFlower123! -i /scripts/CreateFlowershopDatabase.sql
        echo 'Database initialization completed!'
      "
    restart: "no"

  # .NET Backend API  
  api:
    container_name: platformflower-api
    image: ghcr.io/dungzum22/swp391-be:latest
    depends_on:
      - db-init
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver;Initial Catalog=Flowershop;User ID=sa;Password=PlatformFlower123!;Encrypt=True;Trust Server Certificate=True
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - VNPay__ApiUrl=${VNPAY_API_URL}
      - VNPay__TmnCode=${VNPAY_TMN_CODE}
      - VNPay__HashSecret=${VNPAY_HASH_SECRET}
      - VNPay__ReturnUrl=${VNPAY_RETURN_URL}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL}
      - EmailSettings__SenderEmail=${EMAIL_SENDER_EMAIL}
      - EmailSettings__SenderPassword=${EMAIL_SENDER_PASSWORD}
      - EmailSettings__SmtpServer=${EMAIL_SMTP_SERVER}
      - EmailSettings__Port=${EMAIL_PORT}
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    ports:
      - "6784:8080"
    networks:
      - platformflower-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s

volumes:
  sqlserver_data:
    driver: local

networks:
  platformflower-network:
    driver: bridge