name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - PlatformFlower/**
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: |
          docker buildx build . \
            -t ghcr.io/${{ github.repository_owner }}/swp391-backend:latest \
            --platform=linux/amd64,linux/arm64 \
            --push
